[package]
name = "todo-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "3.0.0"
console = "0.16.0"
chrono = "0.4.42"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"